[environments.production.build]
builder = "NIXPACKS"
watchPatterns = ["backend/**"]

[environments.production.build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[environments.production.deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
