[environments.production.build]
builder = "NIXPACKS"
watchPatterns = ["wingaesthetic/**"]

[environments.production.build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[environments.production.build.nixpacksPlan.phases.install]
cmds=["yarn install"]

[environments.production.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
